export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'

export const GET_FEATURED_POSTS = 'GET_FEATURED_POSTS'
export const GET_NEWS_POSTS = 'GET_NEWS_POSTS'
export const GET_EVENT_POSTS = 'GET_EVENT_POSTS'

export const SET_CURRENT = 'SET_CURRENT'
export const GET_CURRENT = 'GET_CURRENT'
export const CLEAR_CURRENT = 'CLEAR_CURRENT'
export const SET_LOADING = 'SET_LOADING'
export const SEARCH_POSTS = 'SEARCH_POSTS'
export const POSTS_ERROR = 'POSTS_ERROR'

// New
export const FETCH_POSTS_REQUEST = '  FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = '  FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = '  FETCH_POSTS_ERROR'

export const CREATE_POSTS_REQUEST = '  CREATE_POSTS_REQUEST'
export const CREATE_POSTS_SUCCESS = '  CREATE_POSTS_SUCCESS'
export const CREATE_POSTS_ERROR = '  CREATE_POSTS_ERROR'
